Release 1.0.0 with TCP Support and Dynamic Types
eProsima/Integration-Service-Deprecated pull request #1
Opened 2018-10-30 07:51 UTC by JuanCarlos-eProsima

[Refs #3571](https://eprosima.easyredmine.com/issues/3571) Implementation of the Release 1.0.0 with the new features implemented in Fast-RTPS including

- TCP Transports
- Dynamic Types support

2018-10-31 08:23 UTC, richiware requested changes

2018-10-31 08:23 UTC, richiware commented on CMakeLists.txt
> +#set(PROJECT_MAJOR_VERSION 0)
Remove these obsoletes comments.

2018-10-31 08:23 UTC, richiware commented on CMakeLists.txt
> +include(${PROJECT_SOURCE_DIR}/cmake/common/eprosima_libraries.cmake)
You are including this cmake file, but you're not using `eprosima_find_package` instead `find_package` for fastcdr and fastrtps.

2018-10-31 08:23 UTC, richiware commented on CMakeLists.txt
> +#set(LICENSE_INSTALL_DIR ./ CACHE PATH "Installation directory for licenses")
where is the license installed?

2018-10-31 08:23 UTC, richiware commented on CMakeLists.txt
> +    include_directories("${fastrtps_INCLUDE_DIR}")
this is not necessary. including targets fastcdr and fastrtps in `target_link_libraries` already includes the include directory.

2018-10-31 08:23 UTC, richiware commented on CMakeLists.txt
> +    add_library(${SHAREDLIB_NAME} SHARED ${${PROJECT_NAME}_source_files})
Join win32 and unix condition. Use for this cmake generator expressions. You can see an example on fastrtps develop branch.

2018-10-31 08:23 UTC, richiware commented on CMakeLists.txt
> +    if(EPROSIMA_INSTALLER)
When the installation is being built, the library doesn't have to be compiled. This is not the case. See fastrtps cmakelists.txt to do the same.

2018-10-31 08:23 UTC, richiware commented on CMakeLists.txt
> +        src/xmlUtils.h
Include headers to be used for users should be in a `include` path like other products.

2018-10-31 08:23 UTC, richiware commented on CMakeLists.txt
> +            src/xmlUtils.h
This installation is already done upper.

2018-10-31 08:23 UTC, richiware commented on CMakeLists.txt
> +            src/main.cpp
Why the source code is installed?

2018-10-31 08:23 UTC, richiware commented on cmake/modules/Findandroid-ifaddrs.cmake
> +# ANDROID_IFADDRS_FOUND
Did you use this file?

2018-10-31 08:32 UTC, JuanCarlos-eProsima commented on CMakeLists.txt
> +#set(PROJECT_MAJOR_VERSION 0)
Removed

2018-10-31 11:29 UTC, LuisGP commented on CMakeLists.txt
> +include(${PROJECT_SOURCE_DIR}/cmake/common/eprosima_libraries.cmake)
Now using `eprosima_find_package`.

2018-10-31 11:31 UTC, LuisGP commented on CMakeLists.txt
> +#set(LICENSE_INSTALL_DIR ./ CACHE PATH "Installation directory for licenses")
Modified to be like Fast-RTPS.

2018-10-31 11:31 UTC, LuisGP commented on CMakeLists.txt
> +    include_directories("${fastrtps_INCLUDE_DIR}")
Fixed.

2018-10-31 11:32 UTC, LuisGP commented on CMakeLists.txt
> +    add_library(${SHAREDLIB_NAME} SHARED ${${PROJECT_NAME}_source_files})
Joined.

2018-10-31 11:32 UTC, LuisGP commented on CMakeLists.txt
> +    if(EPROSIMA_INSTALLER)
Fixed.

2018-10-31 11:33 UTC, LuisGP commented on CMakeLists.txt
> +            src/main.cpp
To generate autotools package on linux. Improved section.

2018-10-31 11:33 UTC, LuisGP commented on cmake/modules/Findandroid-ifaddrs.cmake
> +# ANDROID_IFADDRS_FOUND
Nope, removed.

2018-11-26 08:17 UTC, richiware approved these changes

2018-11-26 08:17 UTC, merged