[4021] Update installer scripts for IS
eProsima/Integration-Service-Deprecated pull request #13
Opened 2018-12-24 08:54 UTC by JuanCarlos-eProsima

Update cmake scripts to generate the installer for IS

2018-12-26 13:56 UTC, richiware submitted a review, later dismissed

2018-12-27 09:14 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Integration-Service%20Manual%20Linux&build=24)](http://jenkins.eprosima.com:8080/job/Integration-Service%20Manual%20Linux/24/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Integration-Service%20Manual%20Windows&build=36)](http://jenkins.eprosima.com:8080/job/Integration-Service%20Manual%20Windows/36/)

2018-12-27 10:01 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Integration-Service%20Manual%20Linux&build=26)](http://jenkins.eprosima.com:8080/job/Integration-Service%20Manual%20Linux/26/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Integration-Service%20Manual%20Windows&build=38)](http://jenkins.eprosima.com:8080/job/Integration-Service%20Manual%20Windows/38/)

2018-12-27 11:13 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Integration-Service%20Manual%20Linux&build=27)](http://jenkins.eprosima.com:8080/job/Integration-Service%20Manual%20Linux/27/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Integration-Service%20Manual%20Windows&build=39)](http://jenkins.eprosima.com:8080/job/Integration-Service%20Manual%20Windows/39/)

2018-12-27 11:46 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Integration-Service%20Manual%20Linux&build=28)](http://jenkins.eprosima.com:8080/job/Integration-Service%20Manual%20Linux/28/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Integration-Service%20Manual%20Windows&build=40)](http://jenkins.eprosima.com:8080/job/Integration-Service%20Manual%20Windows/40/)

2018-12-27 13:00 UTC, richiware requested changes

2018-12-27 13:00 UTC, richiware commented on CMakeLists.txt
> +    if(NOT CMAKE_BUILD_TYPE)
I think is better not to force to compile examples only in Debug. Leave this decision to the user. Remove this part.

2018-12-27 15:52 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Integration-Service%20Manual%20Linux&build=29)](http://jenkins.eprosima.com:8080/job/Integration-Service%20Manual%20Linux/29/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Integration-Service%20Manual%20Windows&build=41)](http://jenkins.eprosima.com:8080/job/Integration-Service%20Manual%20Windows/41/)

2018-12-31 08:05 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Integration-Service%20Manual%20Linux&build=31)](http://jenkins.eprosima.com:8080/job/Integration-Service%20Manual%20Linux/31/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Integration-Service%20Manual%20Windows&build=43)](http://jenkins.eprosima.com:8080/job/Integration-Service%20Manual%20Windows/43/)

2018-12-31 09:15 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Integration-Service%20Manual%20Linux&build=32)](http://jenkins.eprosima.com:8080/job/Integration-Service%20Manual%20Linux/32/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Integration-Service%20Manual%20Windows&build=44)](http://jenkins.eprosima.com:8080/job/Integration-Service%20Manual%20Windows/44/)

2018-12-31 10:00 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Integration-Service%20Manual%20Linux&build=33)](http://jenkins.eprosima.com:8080/job/Integration-Service%20Manual%20Linux/33/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Integration-Service%20Manual%20Windows&build=45)](http://jenkins.eprosima.com:8080/job/Integration-Service%20Manual%20Windows/45/)

2018-12-31 10:35 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Integration-Service%20Manual%20Linux&build=34)](http://jenkins.eprosima.com:8080/job/Integration-Service%20Manual%20Linux/34/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Integration-Service%20Manual%20Windows&build=46)](http://jenkins.eprosima.com:8080/job/Integration-Service%20Manual%20Windows/46/)

2018-12-31 14:13 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Integration-Service%20Manual%20Linux&build=35)](http://jenkins.eprosima.com:8080/job/Integration-Service%20Manual%20Linux/35/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Integration-Service%20Manual%20Windows&build=47)](http://jenkins.eprosima.com:8080/job/Integration-Service%20Manual%20Windows/47/)

2018-12-31 14:34 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Integration-Service%20Manual%20Linux&build=36)](http://jenkins.eprosima.com:8080/job/Integration-Service%20Manual%20Linux/36/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Integration-Service%20Manual%20Windows&build=48)](http://jenkins.eprosima.com:8080/job/Integration-Service%20Manual%20Windows/48/)

2018-12-31 14:56 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Integration-Service%20Manual%20Linux&build=37)](http://jenkins.eprosima.com:8080/job/Integration-Service%20Manual%20Linux/37/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Integration-Service%20Manual%20Windows&build=49)](http://jenkins.eprosima.com:8080/job/Integration-Service%20Manual%20Windows/49/)

2018-12-31 15:08 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Integration-Service%20Manual%20Linux&build=38)](http://jenkins.eprosima.com:8080/job/Integration-Service%20Manual%20Linux/38/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Integration-Service%20Manual%20Windows&build=50)](http://jenkins.eprosima.com:8080/job/Integration-Service%20Manual%20Windows/50/)

2019-01-02 07:01 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Integration-Service%20Manual%20Linux&build=41)](http://jenkins.eprosima.com:8080/job/Integration-Service%20Manual%20Linux/41/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Integration-Service%20Manual%20Windows&build=51)](http://jenkins.eprosima.com:8080/job/Integration-Service%20Manual%20Windows/51/)

2019-01-03 14:28 UTC, JuanCarlos-Arce commented on CMakeLists.txt
> +    if(NOT CMAKE_BUILD_TYPE)
Changed

2019-01-03 14:37 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Integration-Service%20Manual%20Linux&build=46)](http://jenkins.eprosima.com:8080/job/Integration-Service%20Manual%20Linux/46/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Integration-Service%20Manual%20Windows&build=56)](http://jenkins.eprosima.com:8080/job/Integration-Service%20Manual%20Windows/56/)

2019-01-03 15:13 UTC, richiware commented
Build status:
* Linux [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Integration-Service%20Manual%20Linux&build=47)](http://jenkins.eprosima.com:8080/job/Integration-Service%20Manual%20Linux/47/)
* Windows [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=Integration-Service%20Manual%20Windows&build=57)](http://jenkins.eprosima.com:8080/job/Integration-Service%20Manual%20Windows/57/)

2019-01-04 07:05 UTC, JuanCarlos-eProsima commented
We have fixed an issue to generate the Linux installer

2019-01-08 15:23 UTC, richiware approved these changes

2019-01-08 15:24 UTC, merged