Feature/wan example
eProsima/Integration-Service-Deprecated pull request #14
Opened 2019-01-14 08:40 UTC by LuisGP

Added new WAN example using Fast-RTPS's HellowWorld example.

2019-01-22 11:13 UTC, richiware requested changes

2019-01-22 11:13 UTC, richiware commented on examples/wan_example/README.rst
> +incoming TCP connections to port 5100 (you can modify this port in the XML configuration files if you prefer
specify which xml file and put the xml piece code directly here.

2019-01-22 11:13 UTC, richiware commented on examples/wan_example/README.rst
> +**Preparation**
In section *Preparation*. Create a image similar the you already use, but with a configuration example (in the image have to appear the IPs and port of the example) and also put the xml file the user has to change and directly the xml code pieces where the user has to write.

2019-01-23 06:29 UTC, JuanCarlos-Arce commented on examples/wan_example/README.rst
> +incoming TCP connections to port 5100 (you can modify this port in the XML configuration files if you prefer
We have added two includes with the sections that must be updated from each configuration file

2019-01-23 06:29 UTC, JuanCarlos-Arce commented on examples/wan_example/README.rst
> +**Preparation**
We have updated the existing diagram to add more information about the IPs

2019-01-23 10:35 UTC, richiware requested changes

2019-01-23 10:35 UTC, richiware commented on CMakeLists.txt
> +install(FILES ${PROJECT_SOURCE_DIR}/build/${CMAKE_BUILD_TYPE}/integration_service.exe
use `install(TARGETS...`

2019-01-23 10:35 UTC, richiware commented on examples/domain_change/CMakeLists.txt
> +include(${PROJECT_SOURCE_DIR}/../../cmake/common/eprosima_libraries.cmake)
Remove this because not works when the example is compiled isolated. Use the variables `_FOUND`

2019-01-23 10:35 UTC, richiware commented on examples/dynamic_types/CMakeLists.txt
> +    ARCHIVE DESTINATION examples/${PROJECT_NAME}/build$<$<BOOL:${WIN32}>:/${CMAKE_BUILD_TYPE}>
Put also `RUNTIME`

2019-01-23 10:35 UTC, richiware commented on examples/wan_example/README.rst
> +applications running over different subnetworks through a WAN connection. To do that we need at least two
Separate sentences in this document

2019-01-23 11:04 UTC, JuanCarlos-eProsima commented on CMakeLists.txt
> +install(FILES ${PROJECT_SOURCE_DIR}/build/${CMAKE_BUILD_TYPE}/integration_service.exe
Changed

2019-01-23 11:05 UTC, JuanCarlos-eProsima commented on examples/domain_change/CMakeLists.txt
> +include(${PROJECT_SOURCE_DIR}/../../cmake/common/eprosima_libraries.cmake)
We have applied the same management as the examples of Fast-RTPS for these packages

2019-01-23 11:10 UTC, JuanCarlos-eProsima commented on examples/dynamic_types/CMakeLists.txt
> +    ARCHIVE DESTINATION examples/${PROJECT_NAME}/build$<$<BOOL:${WIN32}>:/${CMAKE_BUILD_TYPE}>
Updated in all the examples

2019-01-23 11:13 UTC, JuanCarlos-eProsima commented on examples/wan_example/README.rst
> +applications running over different subnetworks through a WAN connection. To do that we need at least two
Updated

2019-01-23 12:30 UTC, richiware approved these changes

2019-01-23 12:30 UTC, merged